### ISSUE TITLE
idea2020.1无法使用

### ISSUE THREAD

**Issue by harvies** [xxxtai/arthas-hotswap#3]
![image](https://user-images.githubusercontent.com/16585330/88369365-6b8d6700-cdc2-11ea-9dd5-93283eb50b25.png)
![image](https://user-images.githubusercontent.com/16585330/88369382-77792900-cdc2-11ea-841d-c4ddd9835da1.png)

**Comment by xxxtai** [comment]
我已经打包了一个2020.1.3版本的[release](https://github.com/xxxtai/arthas-hotswap/releases/tag/public)，欢迎使用
