### ISSUE TITLE
增加参数可以选择指定的服务

### ISSUE THREAD

**Issue by yun-yun** [xxxtai/arthas-hotswap#7]
现在默认是选择第一个，但是有时候一台会部署多个服务，增加一个服务名称的参数用于选择服务

**Comment by uugit** [comment]
同问作者  请问如何操作 ?
![image](https://user-images.githubusercontent.com/6504355/100873239-f4897d00-34dd-11eb-8267-992910e49ac0.png)
在命令后面 添加什么参数?

**Comment by xxxtai** [comment]
默认选择第一个进程的问题已经解决了，请查看Release v1.1版本。

设置方法：Preference -> Tools -> Arthas Hot Swap，在Enter Java Process中输入需要指定的Java 进程的启动类名。

**Comment by xxxtai** [comment]
可以看最新版本的插件，增加了自定义选择java进程的功能



在 2020-12-02 20:36:54，"uugit" <notifications@github.com> 写道：

同问作者 请问如何操作 ?

在命令后面 添加什么参数?
